services:
  smart-lending:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SERVER_PORT: 8085
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS:--XX:+UseSerialGC -XX:MaxRAMPercentage=70 -XX:InitialRAMPercentage=25 -XX:MinRAMPercentage=25 -XX:+ExitOnOutOfMemoryError -Dfile.encoding=UTF-8}
      PERFORMANCE_STORAGE_PATH: /app/data/performance
    ports:
      - "8085:8085"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped

